//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace redshift_tray.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RedshiftAppPath {
            get {
                return ((string)(this["RedshiftAppPath"]));
            }
            set {
                this["RedshiftAppPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal RedshiftLatitude {
            get {
                return ((decimal)(this["RedshiftLatitude"]));
            }
            set {
                this["RedshiftLatitude"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal RedshiftLongitude {
            get {
                return ((decimal)(this["RedshiftLongitude"]));
            }
            set {
                this["RedshiftLongitude"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5500")]
        public int RedshiftTemperatureDay {
            get {
                return ((int)(this["RedshiftTemperatureDay"]));
            }
            set {
                this["RedshiftTemperatureDay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3500")]
        public int RedshiftTemperatureNight {
            get {
                return ((int)(this["RedshiftTemperatureNight"]));
            }
            set {
                this["RedshiftTemperatureNight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool RedshiftTransition {
            get {
                return ((bool)(this["RedshiftTransition"]));
            }
            set {
                this["RedshiftTransition"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-10000")]
        public double DebugConsoleLeft {
            get {
                return ((double)(this["DebugConsoleLeft"]));
            }
            set {
                this["DebugConsoleLeft"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-10000")]
        public double DebugConsoleTop {
            get {
                return ((double)(this["DebugConsoleTop"]));
            }
            set {
                this["DebugConsoleTop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-10000")]
        public double DebugConsoleWidth {
            get {
                return ((double)(this["DebugConsoleWidth"]));
            }
            set {
                this["DebugConsoleWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-10000")]
        public double DebugConsoleHeight {
            get {
                return ((double)(this["DebugConsoleHeight"]));
            }
            set {
                this["DebugConsoleHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Normal")]
        public global::System.Windows.WindowState DebugConsoleWindowState {
            get {
                return ((global::System.Windows.WindowState)(this["DebugConsoleWindowState"]));
            }
            set {
                this["DebugConsoleWindowState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-10000")]
        public double AboutLeft {
            get {
                return ((double)(this["AboutLeft"]));
            }
            set {
                this["AboutLeft"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-10000")]
        public double AboutTop {
            get {
                return ((double)(this["AboutTop"]));
            }
            set {
                this["AboutTop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-10000")]
        public double SettingsWindowLeft {
            get {
                return ((double)(this["SettingsWindowLeft"]));
            }
            set {
                this["SettingsWindowLeft"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-10000")]
        public double SettingsWindowTop {
            get {
                return ((double)(this["SettingsWindowTop"]));
            }
            set {
                this["SettingsWindowTop"] = value;
            }
        }
    }
}
